### ISSUE TITLE
Zero elements in CGX

### ISSUE THREAD

**Issue by thodec95** [imirzov/gmsh2ccx#2]
Hello everyone,

I’ve just started to learn CalculiX with Gmsh, but it doesnt really work. I opened a simple beam (step-file) with Gmsh and converted it to geo-file by Creating a physical group (Volume). Then I created a 2D-mesh. After that I exported it to an inp-file for reading it with CalculiX Launcher. Finally I converted it to inp-File for Python-script with the launcher. But if I run the CGX-Preprocessor an empty cgx appears with zero elements (like in the picture). Did I do anything wrong?
![8116a001ed3fbbf075b0dae9a54230632cbbc2c4](https://user-images.githubusercontent.com/121199291/231964254-3f602d9e-3eff-4f63-aeba-18224a969693.png)

**Comment by imirzov** [comment]
As far as I know, CalculiX Launcher does not use the gmsh2ccx converter. So you'd better address the question to Launcher's authors.
